### PR TITLE
Crash / messages on every page (I hate my life)

### PR DESCRIPTION
**Pull request by Awashcard0**
This took forever

So on every page it links to `everypage.js` which has my [http message code](https://github.com/Awashcard0/http-crash#js-snippet)

To get it to work for you see the [replit instructions](https://github.com/Awashcard0/http-crash#replit)

### CODE REVIEW

**Comment by mountain658** [comment]
Why would i do that?

**Comment by Awashcard0** [comment]
The main point I thought would be useful to you It was the messaging feature. I have a video demonstration if you would like to see it.

At my school that's popular to crash other people, since we have Chromebooks it just crashes the whole operating system

https://user-images.githubusercontent.com/95319856/232632262-ebe961b9-70ca-4bbf-a851-ce0943407c55.mp4

**Comment by mountain658** [comment]
Hey there! Sorry for the delay in my reply. Thank you so much for taking the time to add your message script to almost 200 files. Your project is really impressive and I just wanted to say that I appreciate all your hard work. That being said, I don't currently think your message script is needed for my website.

I just want to make it clear that I still value your work and contributions. I do plan on using the script file, as it could really help with updating the website's UI across the entire site at once. I never felt the motivation to go and manually add a script file myself, and you did! 😃 

If I end up needing a message system in the future, I will definitely check out your repository. Thank you again for your help!

**Review by mountain658 — APPROVED** [review]
Very good

**Comment by Awashcard0** [comment]
That's what I thought it could be used for if you didn't want the message system.

**Pull request merged**
